(function() {var implementors = {};
implementors['redox'] = ["impl&lt;T&gt; <a class='trait' href='redox/borrow/trait.Borrow.html' title='redox::borrow::Borrow'>Borrow</a>&lt;T&gt; for <a class='struct' href='redox/struct.Box.html' title='redox::Box'>Box</a>&lt;T&gt; <span class='where'>where T: ?<a class='trait' href='redox/marker/trait.Sized.html' title='redox::marker::Sized'>Sized</a></span>","impl&lt;T&gt; <a class='trait' href='redox/borrow/trait.Borrow.html' title='redox::borrow::Borrow'>Borrow</a>&lt;T&gt; for <a class='struct' href='https://doc.rust-lang.org/nightly/alloc/arc/struct.Arc.html' title='alloc::arc::Arc'>Arc</a>&lt;T&gt; <span class='where'>where T: ?<a class='trait' href='redox/marker/trait.Sized.html' title='redox::marker::Sized'>Sized</a></span>","impl&lt;T&gt; <a class='trait' href='redox/borrow/trait.Borrow.html' title='redox::borrow::Borrow'>Borrow</a>&lt;T&gt; for <a class='struct' href='redox/rc/struct.Rc.html' title='redox::rc::Rc'>Rc</a>&lt;T&gt; <span class='where'>where T: ?<a class='trait' href='redox/marker/trait.Sized.html' title='redox::marker::Sized'>Sized</a></span>","impl&lt;'a, B&gt; <a class='trait' href='redox/borrow/trait.Borrow.html' title='redox::borrow::Borrow'>Borrow</a>&lt;B&gt; for <a class='enum' href='redox/borrow/enum.Cow.html' title='redox::borrow::Cow'>Cow</a>&lt;'a, B&gt; <span class='where'>where B: <a class='trait' href='redox/borrow/trait.ToOwned.html' title='redox::borrow::ToOwned'>ToOwned</a> + ?<a class='trait' href='redox/marker/trait.Sized.html' title='redox::marker::Sized'>Sized</a>, B::<a class='trait' href='redox/borrow/trait.ToOwned.html' title='redox::borrow::ToOwned'>Owned</a>: 'a</span>","impl&lt;T&gt; <a class='trait' href='redox/borrow/trait.Borrow.html' title='redox::borrow::Borrow'>Borrow</a>&lt;[T]&gt; for <a class='struct' href='redox/struct.Vec.html' title='redox::Vec'>Vec</a>&lt;T&gt;","impl <a class='trait' href='redox/borrow/trait.Borrow.html' title='redox::borrow::Borrow'>Borrow</a>&lt;str&gt; for <a class='struct' href='redox/string/struct.String.html' title='redox::string::String'>String</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
